# Generated by Django 3.2.5 on 2022-01-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('credit_rating', models.PositiveIntegerField()),
                ('credit_limit', models.PositiveIntegerField()),
                ('credit_balance', models.IntegerField()),
                ('credit_outstanding', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ledgerActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.PositiveIntegerField()),
                ('action_type_id', models.PositiveIntegerField()),
                ('prev_value', models.PositiveIntegerField()),
                ('current_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ledgerActionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ledgerTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.PositiveIntegerField()),
                ('transaction_amount', models.PositiveIntegerField()),
                ('credit_balance', models.IntegerField()),
                ('credit_outstanding', models.IntegerField()),
            ],
        ),
    ]
