# Generated by Django 3.2.5 on 2022-01-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeractions',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgertransactions',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.ledger'),
        ),
    ]
