# Generated by Django 3.2.10 on 2022-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0003_alter_ledger_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransactions',
            name='transaction_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
