# Generated by Django 3.2.10 on 2022-02-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0008_alter_ledger_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='store',
            name='distributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='creditmanagement.distributor'),
        ),
    ]
