# Generated by Django 3.2.10 on 2022-02-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0013_alter_ledger_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='business_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.distributor'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='distributor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.distributor'),
        ),
    ]
