# Generated by Django 3.2.10 on 2022-02-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0014_auto_20220206_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='business_id',
            new_name='distributor_id',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='company_id',
            new_name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='store_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.store'),
        ),
    ]
