# Generated by Django 3.2.10 on 2022-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0015_auto_20220208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='store_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
