# Generated by Django 3.2.10 on 2022-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0016_alter_ledger_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='store',
            name='distributor_id',
            field=models.ManyToManyField(null=True, to='creditmanagement.distributor'),
        ),
    ]
