# Generated by Django 3.2.10 on 2022-02-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0017_auto_20220208_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeractions',
            name='action_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditmanagement.ledgeractiontypes'),
        ),
    ]
