# Generated by Django 3.2.5 on 2022-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
